function seaMap(){
map=[
["air", "air", "air", "air", "air", "air", "air", "air", "dirt_grass", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "lava"],
["air", "air", "air", "air", "air", "air", "air", "air", "air", "dirt_grass", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], 
["air", "air", "air", "air", "air", "air", "air", "air", "air", "air", "dirt_grass", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], 
["air", "air", "air", "air", "air", "air", "air", "air", "dirt", "dirt_grass", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], 
["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "lava"], 
["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "water", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "water", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "water", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "stone"], ["air", "air", "air", "air", "air", "air", "air", "air", "water", "water", "water", "water", "water", "water", "dirt", "dirt", "dirt", "stone", "stone", "stone", "stone", "stone", "stone", "stone", "lava"]]
for(x=0;x<25;x++){
	for(y=0;y<25;y++){
		Act(x,y)
		}
	}
	return "allowed"
}
