function dungeonMap(){
map=[
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","stone","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","stone","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","stone","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","stone","water","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","stone","stone","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","stone","stone","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air","air",],
["air","air","air","air","air","air","air","air","air","air","air","dirt","air","air","air","air","air","air","air","air","air","air","air","air","air",],
];
for(x=0;x<25;x++){
	for(y=0;y<25;y++){
		Act(x,y)
		}
	}
spawn();
return "allowed"
}
